POST http://localhost:3000/api/photos HTTP/1.1
Content-Type: multipart/form-data; boundary=----FormBoundary1234

------FormBoundary1234
Content-Disposition: form-data; name="file"; filename="input.jpg"
Content-Type: image/jpeg

< ./input.jpg

------FormBoundary1234
Content-Disposition: form-data; name="album"
Content-Type: text/plain

user_albumpppp
------FormBoundary1234

### GET
GET http://localhost:3000/api/photos/all HTTP/1.1

### TOKEN
POST http://localhost:3000/api/user/login HTTP/1.1
authorization: Bearer eyJhbG.eyJlbWFpbCII6MTY1MjI4NjgzN30.xkXNNho-MxECZsJXCIU

### REGISTER
POST http://localhost:3000/api/user/register HTTP/1.1
content-type: application/json

{
    "name": "name",
    "lastName": "lastName",
    "email":"name@email.pl",
    "password":"password"
}

### LOGIN
POST http://localhost:3000/api/user/login HTTP/1.1
content-type: application/json

{
    "email":"name@email.pl",
    "password":"password"
}

###aaa
POST http://localhost:3000/api/user/test HTTP/1.1
content-type: application/json

{
    "email":"name@email.pl",
    "password":"password"
}


### Jedno zdjecie
GET http://localhost:3000/api/photos/1716462934513 HTTP/1.1

### Update zdjecia
PATCH http://localhost:3000/api/photos/1716797307981 HTTP/1.1
Content-Type: multipart/form-data; boundary=----FormBoundary1234

------FormBoundary1234
Content-Disposition: form-data; name="file"; filename="input.jpg"
Content-Type: image/jpeg

< ./input.jpg

------FormBoundary1234
Content-Disposition: form-data; name="album"
Content-Type: text/plain

eeee
------FormBoundary1234

### DELETE zdjecia
DELETE http://localhost:3000/api/photos/1716797307981 HTTP/1.1